<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-KHFPL78" failures="1" tests="1" name="com.runners.UserLoginTestRunner" time="15.776" errors="0" timestamp="2025-03-19T01:57:17 PDT" skipped="0">
  <testcase classname="com.runners.UserLoginTestRunner" name="runScenario" time="15.776">
    <failure message="expected [https://www.letskodeit.com/] but found [https://www.letskodeit.com/login]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.letskodeit.com/] but found [https://www.letskodeit.com/login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.loginsteps.UserLoginStepDefinitions.user_is_on_homepage(UserLoginStepDefinitions.java:57)
at âœ½.User is on homepage(file:///C:/Users/Administrator/Desktop/Capstone_24532/Projectletskodeit/src/test/resources/Features/UserLogin.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- com.runners.UserLoginTestRunner -->
